name: odrs
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  crypto: ^3.0.2
  glib:
    git:
      url: https://github.com/ubuntu-flutter-community/glib.dart.git
  lints: ^2.0.1
  mockito: ^5.3.2
  test: ^1.22.2
