name: odrs
description: Open Desktop Ratings Service (ODRS) client for Dart.
homepage: https://odrs.gnome.org/
repository: https://github.com/ubuntu-flutter-community/odrs.dart
issue_tracker: https://github.com/ubuntu-flutter-community/odrs.dart/issues
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  crypto: ^3.0.2
  glib: ^0.0.0-dev.0
  lints: ^2.0.1
  mockito: ^5.4.0
  test: ^1.22.2
